apiVersion: v1
kind: Secret
metadata:
  name: code-campus-backend-secret
type: Opaque
stringData:
  MONGO_URI: "your-mongodb-connection-string"
  JWT_SECRET: "your-jwt-secret"
  JWT_EXPIRES_IN: "7d"
  CLOUDINARY_CLOUD_NAME: "your-cloudinary-cloud-name"
  CLOUDINARY_API_KEY: "your-cloudinary-api-key"
  CLOUDINARY_API_SECRET: "your-cloudinary-api-secret"
  FRONTEND_URL: "https://code-campus.local"
  ENABLE_LOCAL_EXEC: "false"
  RAPIDAPI_KEY: "your-rapidapi-key"
  JUDGE0_API_KEY: "your-judge0-api-key"
